# Generated by Django 5.0.2 on 2024-02-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backend",
            name="title",
        ),
        migrations.AddField(
            model_name="backend",
            name="image",
            field=models.ImageField(
                default="C:/Users/siyun/OneDrive/Desktop/QMIND 2024/Web_app/qmind_backend/007-0004-000.jpg",
                upload_to="post_images",
            ),
        ),
        migrations.AddField(
            model_name="backend",
            name="name",
            field=models.CharField(default="Unnamed", max_length=100),
        ),
    ]
